### ISSUE TITLE
Change repo name to something more descriptive / consistent?

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe-plugin-googlesearchconsole#2]
Rather than calling this `steampipe-plugin-gsc` I think we should use something more consistent / descriptive.

Our current names are:
* `googledirectory`
* `googlesheets`
* `googleworkspace`

Calling it `googlesearch` feels too much like actual searching ... so perhaps we should go with `googlesearchconsole`?

**Comment by karanpopat** [comment]
Updated the plugin name
